### ISSUE TITLE
error from module

### ISSUE THREAD

**Issue by lsdeep** [Toxic-Noob/ToxicBomber#2]
Hi,
i tried many times to run but get many errors 

>  _____         _      _   _             _     
> |_   _|____  _(_) ___| \ | | ___   ___ | |__  
>   | |/ _ \ \/ / |/ __|  \| |/ _ \ / _ \| '_ \ 
>   | | (_) >  <| | (__| |\  | (_) | (_) | |_) |
>   |_|\___/_/\_\_|\___|_| \_|\___/ \___/|_.__/ 
>                                               
>                      Security Is An Illusion
> 
> Traceback (most recent call last):
>   File "/home/lsdeep/ToxicBomber/Tbomb.py", line 271, in <module>
>     version(verFile = "libs/.version", RepoURL = "https://github.com/Toxic-Noob/ToxicBomber", RepoFile = "Tbomb.py")
>   File "", line 34, in version
>   File "", line 11, in psb
> TypeError: can only concatenate str (not "str_iterator") to str

also i uninstall python modules and install again same error

**Comment by Toxic-Noob** [comment]
Wait for the Update....
