### ISSUE TITLE
an error 

### ISSUE THREAD

**Issue by mssaim7777** [Toxic-Noob/ToxicBomber#5]
আপডেট আসার পর থেক আমি এটা আর ubuntu22.04 LTS এর মধ্যে এই টুল টি  ব্যবহার করতে পারছি না । 
pip install requests কমান্ড দিয়ে .Requirement already satisfied করার পরে ও এই error টা show করে ।
*ModuleNotFoundError: No module named 'requests'* 
এমন কি (vnenv) দিয়ে try করার পরে ও ।

 How do i solve it ???

**Comment by Toxic-Noob** [comment]
Please consider giving a full screenshot of executing pip install requests and the error...

**Comment by mssaim7777** [comment]
![Screenshot from 2022-12-17 16-41-21](https://user-images.githubusercontent.com/120774156/208237963-e84b019a-1f83-47e7-bf70-8feec4b87911.png)

**Comment by mssaim7777** [comment]
![Screenshot from 2022-12-17 16-48-21](https://user-images.githubusercontent.com/120774156/208238105-e9cfd746-857c-4402-b24f-988b1ee8fa3f.png)

**Comment by mssaim7777** [comment]
![image](https://user-images.githubusercontent.com/120774156/208238169-750bf81f-8e29-4107-a368-e7461760f712.png)


এটা venv  ছাড়া ।

**Comment by Toxic-Noob** [comment]
আপনি python ফুল ইন্সটল না করে শুধু 3.11 ভার্সন ইন্সটল করেছেন। তাই pip install কমান্ড দিয়ে যেই মডিউল ইন্সটল করছেন, সেটা আগের ভার্সনে ইন্সটল হচ্ছে, 3.11 ভার্সনে হচ্ছে না।
তাই pkg reinstall python কমান্ড ইউজ করে python 3.11 ফুল ইন্সটল দিন। তাহলে কাজ করবে...

**Comment by mssaim7777** [comment]
How do i fix it ???

root@ubuntu2468:/home/mssaim# pkg reinstall python
Command 'pkg' not found, did you mean:
  command 'pig' from deb bsdgames (2.17-29)
  command 'pk4' from deb pk4 (5build2)
  command 'pki' from deb strongswan-pki (5.9.5-2ubuntu2.1)
  command 'pki' from deb pki-tools (11.0.0-1)
  command 'zkg' from deb zkg (2.12.0-1)
  command 'peg' from deb peg (0.1.18-1)
  command 'pmg' from deb python3-pymatgen (2022.0.17+dfsg1-1build1)
  command 'dpkg' from deb dpkg (1.21.1ubuntu2.1)
Try: apt install <deb name>
root@ubuntu2468:/home/mssaim#

**Comment by mssaim7777** [comment]
![Screenshot ](https://user-images.githubusercontent.com/120774156/208243691-a30eb6bd-a142-421e-ae75-ff9fc23cd5f2.png)

how do i fix it ???

**Comment by Toxic-Noob** [comment]
You are in Ubuntu! 😪

Try checking this tutorial: https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

Note: Updated python version is 3.11. So replace 3.10 with 3.11 from the tutorial

**Comment by mssaim7777** [comment]
thanks a lot... 
its work.
